apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  name: podtato-head-kubectl-promise
spec:
  xaasRequestPipeline:
    - podtato-head:kubectl
  xaasCrd:
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: podtato-head-kubectl.promise.example.com
    spec:
      group: promise.example.com
      scope: Namespaced
      names:
        plural: podtato-head-kubectls
        singular: podtato-head-kubectl
        kind: podtato-head-kubectl
      versions:
        - name: v1
          served: true
          storage: true
  workerClusterResources:
    - apiVersion: v1
      kind: Namespace
      metadata:
        name: podtato-kubectl
